# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Microservices
tagline:          'V1'
description:      'Microservices with Azure, ASP.NET and Xamarin'
url:              https://microservices.rclapp.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'RCL (Anil Ripla)'
  url:            https://microservices.rclapp.com

# Custom vars
version:            3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/rcl-microservices-aks

disqus:
  shortname: rcl-micro-service

google_analytics: 'UA-101288551-5'
